name: Build

on:
  push
  
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20.x'

      - name: Install dependencies
        run: npm ci

      - name: Build 
        run: npm run build

      - name: Pack  
        run: npm run pack

      - run: ls -l dist/

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: archives
          path: dist/*.zip